name: syncx

description: >
  Flutter state management made easy: SyncX is a lightweight, flexible solution with notifiers, builders, and consumers for reactive UI updates. Inspired by provider, bloc, and riverpod.

version: 0.0.82

homepage: https://github.com/sidha6th/sync-x
repository: https://github.com/sidha6th/sync-x
issue_tracker: https://github.com/sidha6th/sync-x/issues
documentation: https://github.com/sidha6th/sync-x#readme

topics:
  - state-management
  - notifier
  - reactive
  - state
  - state-management-library

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter: { sdk: flutter }
  provider: ^6.1.5

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^5.0.0
# Exclude files from the published package
# (add more patterns as needed)
#
# files:
#   - lib/
#   - README.md
#   - CHANGELOG.md
#   - LICENSE
